# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(choices=[(0, 'canceled'), (1, 'pending'), (2, 'completed')]),
        ),
        migrations.AlterField(
            model_name='deliverygroup',
            name='status',
            field=models.IntegerField(choices=[(0, 'canceled'), (1, 'pending'), (2, 'completed')]),
        ),
    ]
