# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
