# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20160920_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioitemresourcestock',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ioproductstock',
            name='note',
            field=models.TextField(default=datetime.datetime(2016, 9, 22, 19, 30, 1, 613583, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ioitemresourcestock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ioproductstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemresourcestock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
