# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20160922_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioitemresourcestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.ItemResourceStock'),
        ),
        migrations.AlterField(
            model_name='ioproductstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.ProductStock'),
        ),
        migrations.AlterField(
            model_name='itemresourcestock',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='item_resource.ItemResource'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.Product'),
        ),
    ]
