# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20160926_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioitemresourcestock',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ioproductstock',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
