# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('account_balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=20)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_balance.Balance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
