# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'canceled'), (1, 'pending'), (2, 'completed'), (3, 'issued')], default=1),
        ),
    ]
